### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by slonoed** [bearded-web/frontend#53]
- [x] CRUD for project #54
- [ ] Add participant to project (+remove) #55
- [ ] Show participants in project page #56
- [ ] Show participants in project on left panel #57
- [ ] Show scans chart on project page (issues detect chart?) #58
- [ ] Show issues counts on target in left panel #59
- [ ] Add comments to scan (feed item?) #45
- [ ] Show scan data (issues and techs) in feed #60
- [ ] Show in feed user added to project (removed?) #61
- [ ] Show in feed issues closed #62
- [ ] Bug with report #52
- [ ] Fix typos and grammars #41

**Comment by slonoed** [comment]
~~@m0sth8 all commits now to branch `demo`. Directly of with PR~~
`master`

**Comment by slonoed** [comment]
work with milestome
