### ISSUE TITLE
Target issues

### ISSUE THREAD

**Issue by slonoed** [bearded-web/frontend#78]
Backend task https://github.com/bearded-web/bearded/issues/36
- Target status page
- High, medium, low
- Close issue
- Mute issue
- Issues categories

**Tasks**
- [x] Create issues content store #83
- [x] Create issues list store #84
- [x] Create IssuesPage component #85
- [x] Create IssuePage #90
- [x] Issues list items controls #93
- [x] Issues total in target page #94
